import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configurada para documentação de produto do Educacross.
 * Organização: Visão → Personas → Fluxos → Jornadas → Protótipos → Técnico
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // === DOCUMENTAÇÃO DE PRODUTO ===
    {
      type: 'category',
      label: 'Visão do Produto',
      collapsed: false,
      items: [
        'produto/index',
        'produto/design-process',
      ],
    },
    {
      type: 'category',
      label: 'Personas',
      collapsed: false,
      items: [
        'personas/index',
        'personas/professor',
        'personas/aluno',
        'personas/administrator',
        'personas/coordinator',
        'personas/director',
        'personas/network-manager',
      ],
    },
    {
      type: 'category',
      label: 'Fluxos Críticos',
      collapsed: false,
      items: [
        'fluxos/index',
        'fluxos/aceitar-recusar-perfil',
        'fluxos/habilitar-missoes',
        'fluxos/completar-missao',
        'fluxos/gerar-relatorio',
      ],
    },
    
    // === JORNADAS POR PERSONA ===
    {
      type: 'category',
      label: 'Jornadas',
      collapsed: true,
      items: [
        'journeys/index',
        'journeys/intro',
        {
          type: 'category',
          label: 'Professor',
          items: [{type: 'autogenerated', dirName: 'journeys/teacher'}],
        },
        {
          type: 'category',
          label: 'Administrador',
          items: [{type: 'autogenerated', dirName: 'journeys/administrator'}],
        },
        {
          type: 'category',
          label: 'Coordenador',
          items: [{type: 'autogenerated', dirName: 'journeys/coordinator'}],
        },
        {
          type: 'category',
          label: 'Diretor',
          items: [{type: 'autogenerated', dirName: 'journeys/director'}],
        },
        {
          type: 'category',
          label: 'Gestor de Rede',
          items: [{type: 'autogenerated', dirName: 'journeys/network-manager'}],
        },
        {
          type: 'category',
          label: 'Estudante',
          items: [{type: 'autogenerated', dirName: 'journeys/student'}],
        },
      ],
    },
    
    // === PROTÓTIPOS ===
    {
      type: 'category',
      label: '🎨 Protótipos',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'prototypes'}],
    },
    
    // === DISCOVERY / PESQUISA ===
    {
      type: 'category',
      label: '🔬 Discovery',
      collapsed: true,
      items: [
        'discovery/index',
        'discovery/professor',
        'discovery/gestor',
        'discovery/aluno',
      ],
    },
    
    // === DOCUMENTAÇÃO TÉCNICA ===
    {
      type: 'category',
      label: '🏗️ Arquitetura',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: '🎨 Design System',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'design-system'}],
    },
    {
      type: 'category',
      label: '📖 Guias',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
  ],
};

export default sidebars;
